server:
  port: 5000
spring:
  application:
    name: Eureka-Server
 
    
---
spring:
  profiles: eurekaone
  
server:
  port: 5001
eureka:
  instance:
    hostname: eureka-primary
    appname: eone
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka-secondary:5002/eureka,http://eureka-tertiary:5003/eureka

---
spring:
  profiles: eurekatwo
  
server:
  port: 5002
eureka:
  instance:
    hostname: eureka-secondary
    appname: eone
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka-primary:5001/eureka,http://eureka-tertiary:5003/eureka
      
---
spring:
  profiles: eurekathree
  
server:
  port: 5003
eureka:
  instance:
    hostname: eureka-tertiary
    appname: eone
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka-primary:5001/eureka,http://eureka-secondary:5002/eureka
      